### ISSUE TITLE
Development of Task: Change Password Big

### ISSUE THREAD

**Issue by GeorgeCrochiere** [GeorgeCrochiere/ee368-mango#7]

**Comment by elisealm2** [comment]
On 4/10 commit I (elise) completed code using George's computer.  

Changed a portion of line 150 in UserDao.java. 

https://github.com/GeorgeCrochiere/ee368-mango/tree/password

https://github.com/GeorgeCrochiere/ee368-mango/compare/main...GeorgeCrochiere:ee368-mango:password
