### ISSUE TITLE
Development of Task: Horizontal CSV

### ISSUE THREAD

**Issue by GeorgeCrochiere** [GeorgeCrochiere/ee368-mango#9]

**Comment by cVita66** [comment]
4/10/2024 Update:

Current sub-branch: 
https://github.com/GeorgeCrochiere/ee368-mango/tree/horizontal_csv

1.  Unique point data is print to sub-column groups in '.csv' generation
2.  Unique points are ordered alphabetically from left to right
3.  Empty cells precede subsequent data points if greater quantity of point data exists in the database
4.  Five headers maintained for each unique data point
5.  Duplicate data not known to be present when printing
6.  Empty data sets not printed

VC
